# Generated by Django 5.0.6 on 2026-09-06 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('DNS_OBSERVATION', 'DNS Observation'), ('DNS_RECORD', 'DNS Record'), ('IP_ADDRESS', 'IP Address'), ('CERTIFICATE', 'Certificate'), ('SERVICE', 'Service'), ('ASN', 'ASN'), ('PROVIDER', 'Provider'), ('ALERT', 'Alert'), ('LIFECYCLE_ASSESSMENT', 'Lifecycle Assessment'), ('ANALYST_NOTE', 'Analyst Note')], max_length=50)),
                ('status', models.CharField(choices=[('OBSERVED', 'Observed'), ('HISTORICAL', 'Historical'), ('INFERRED', 'Inferred'), ('ANALYST', 'Analyst'), ('UNKNOWN', 'Unknown')], default='OBSERVED', max_length=20)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(default='Unknown', help_text="Source of the evidence (e.g., 'Public DNS', 'RDAP', 'TLS Handshake')", max_length=100)),
                ('collection_method', models.CharField(blank=True, help_text='How the evidence was collected', max_length=100)),
                ('observation', models.TextField(help_text='The actual observation or finding')),
                ('entity_name', models.CharField(blank=True, help_text='Name of the entity this evidence relates to', max_length=255)),
                ('entity_type', models.CharField(blank=True, help_text='Type of entity (domain, IP, certificate, etc.)', max_length=50)),
                ('related_object_id', models.UUIDField(blank=True, help_text='ID of related object in its own table', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object (app_label.model)', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured metadata about the evidence')),
                ('observed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the evidence was observed')),
                ('first_observed', models.DateTimeField(auto_now_add=True, help_text='First time this evidence was observed')),
                ('last_observed', models.DateTimeField(auto_now=True, help_text='Most recent observation timestamp')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='dns_intelligence.domain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(help_text="Type of relationship (e.g., 'resolves_to', 'secured_by')", max_length=100)),
                ('confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('from_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='lifecycle.evidence')),
                ('to_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='lifecycle.evidence')),
            ],
            options={
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('ACTIVE', 'Active'), ('LEGACY', 'Legacy'), ('POTENTIALLY_ABANDONED', 'Potentially Abandoned'), ('LIKELY_ABANDONED', 'Likely Abandoned'), ('UNKNOWN', 'Unknown')], max_length=30)),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Confidence score (0.00-1.00)', max_digits=3)),
                ('supporting_evidence', models.JSONField(blank=True, default=list, help_text='List of evidence IDs supporting this classification')),
                ('contradicting_evidence', models.JSONField(blank=True, default=list, help_text='List of evidence IDs contradicting this classification')),
                ('model_version', models.CharField(default='1.0', help_text='Version of the classification model used', max_length=50)),
                ('limitations', models.TextField(blank=True, help_text='Known limitations or missing data that affected this classification')),
                ('explanation', models.TextField(blank=True, help_text='Human-readable explanation of the classification')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_assessments', to='dns_intelligence.domain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['domain', 'evidence_type', 'observed_at'], name='lifecycle_e_domain__4efa71_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['owner', 'evidence_type'], name='lifecycle_e_owner_i_ae6e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['status'], name='lifecycle_e_status_95ff3b_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['confidence'], name='lifecycle_e_confide_32085d_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['source'], name='lifecycle_e_source_d1e7db_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerelationship',
            index=models.Index(fields=['from_evidence', 'relationship_type'], name='lifecycle_e_from_ev_f60ca2_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencerelationship',
            index=models.Index(fields=['to_evidence', 'relationship_type'], name='lifecycle_e_to_evid_9327e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evidencerelationship',
            unique_together={('from_evidence', 'to_evidence', 'relationship_type')},
        ),
        migrations.AddIndex(
            model_name='lifecycleassessment',
            index=models.Index(fields=['domain', '-generated_at'], name='lifecycle_l_domain__1955a6_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecycleassessment',
            index=models.Index(fields=['classification'], name='lifecycle_l_classif_99d623_idx'),
        ),
        migrations.AddIndex(
            model_name='lifecycleassessment',
            index=models.Index(fields=['owner', 'classification'], name='lifecycle_l_owner_i_3a0da1_idx'),
        ),
    ]
