# Generated by Django 5.0.6 on 2026-08-27 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('authorized', models.BooleanField(default=True, help_text='User attestation that they are authorized to investigate this domain.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DNSFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_findings', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('DNS_DISCOVERY', 'DNS discovery'), ('DNS_ANALYSIS', 'DNS analysis'), ('CERTIFICATE_ANALYSIS', 'Certificate analysis'), ('INFRASTRUCTURE_ANALYSIS', 'Infrastructure analysis'), ('SERVICE_OBSERVATION', 'Service observation'), ('LIFECYCLE_CLASSIFICATION', 'Lifecycle classification'), ('FULL_INVESTIGATION', 'Full investigation')], max_length=40)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('progress_steps', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNSRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('CNAME', 'CNAME'), ('NS', 'NS'), ('MX', 'MX'), ('TXT', 'TXT'), ('SOA', 'SOA'), ('CAA', 'CAA'), ('PTR', 'PTR'), ('DNSKEY', 'DNSKEY'), ('DS', 'DS')], max_length=10)),
                ('value', models.TextField()),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_records', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['hostname', 'record_type'],
                'indexes': [models.Index(fields=['hostname', 'record_type'], name='dns_intelli_hostnam_613710_idx')],
            },
        ),
        migrations.CreateModel(
            name='DNSObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_index=True, max_length=255)),
                ('record_type', models.CharField(max_length=10)),
                ('values', models.JSONField(default=list)),
                ('response_code', models.CharField(blank=True, max_length=20)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('resolver_used', models.CharField(blank=True, max_length=64)),
                ('query_time_ms', models.FloatField(blank=True, null=True)),
                ('dnssec_signed', models.BooleanField(null=True)),
                ('source', models.CharField(default='Public DNS', max_length=64)),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='HIGH', max_length=10)),
                ('observed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_observations', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['domain', 'hostname', 'record_type', 'observed_at'], name='dns_intelli_domain__5e33d0_idx')],
            },
        ),
    ]
