# Generated by Django 5.0.6 on 2026-09-08 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address where service was observed')),
                ('port', models.IntegerField(help_text='Port number')),
                ('protocol', models.CharField(help_text='Protocol (TCP, UDP, etc.)', max_length=20)),
                ('service_type', models.CharField(help_text='Service type (HTTP, HTTPS, SSH, etc.)', max_length=50)),
                ('is_available', models.BooleanField(default=True, help_text='Whether the service is currently available')),
                ('http_status', models.IntegerField(blank=True, help_text='HTTP status code if applicable', null=True)),
                ('response_time_ms', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('service_banner', models.TextField(blank=True, help_text='Service banner or version information')),
                ('ssl_tls_enabled', models.BooleanField(default=False, help_text='Whether SSL/TLS is enabled')),
                ('source', models.CharField(default='Service Observation', help_text='Source of service data', max_length=100)),
                ('collection_timestamp', models.DateTimeField(auto_now_add=True, help_text='When this service was observed')),
                ('first_observed', models.DateTimeField(auto_now_add=True)),
                ('last_observed', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['-last_observed'],
                'indexes': [models.Index(fields=['domain', '-last_observed'], name='services_se_domain__d5e838_idx'), models.Index(fields=['ip_address', 'port'], name='services_se_ip_addr_52ef3f_idx'), models.Index(fields=['service_type'], name='services_se_service_9fa833_idx'), models.Index(fields=['is_available'], name='services_se_is_avai_db1380_idx')],
                'unique_together': {('domain', 'ip_address', 'port', 'protocol')},
            },
        ),
        migrations.CreateModel(
            name='ServiceObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=20)),
                ('service_type', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('service_banner', models.TextField(blank=True)),
                ('ssl_tls_enabled', models.BooleanField(default=False)),
                ('source', models.CharField(default='Service Observation', max_length=100)),
                ('collection_method', models.CharField(blank=True, help_text='How the service was observed', max_length=100)),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM', max_length=10)),
                ('observed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_observations', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['domain', 'ip_address', 'port', 'observed_at'], name='services_se_domain__008503_idx'), models.Index(fields=['domain', '-observed_at'], name='services_se_domain__f33fab_idx'), models.Index(fields=['service_type'], name='services_se_service_93dd92_idx')],
            },
        ),
    ]
