# Generated by Django 5.0.6 on 2026-09-11 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns_intelligence', '0001_initial'),
        ('investigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('DNS_RECORD_ADDED', 'DNS Record Added'), ('DNS_RECORD_REMOVED', 'DNS Record Removed'), ('DNS_RECORD_CHANGED', 'DNS Record Changed'), ('IP_CHANGED', 'IP Changed'), ('CERTIFICATE_CHANGED', 'Certificate Changed'), ('CERTIFICATE_EXPIRED', 'Certificate Expired'), ('CERTIFICATE_EXPIRING_SOON', 'Certificate Expiring Soon'), ('SERVICE_APPEARED', 'Service Appeared'), ('SERVICE_DISAPPEARED', 'Service Disappeared'), ('ASN_CHANGED', 'ASN Changed'), ('PROVIDER_CHANGED', 'Provider Changed'), ('LIFECYCLE_CHANGED', 'Lifecycle Changed')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('OPEN', 'Open'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='NEW', max_length=20)),
                ('title', models.CharField(help_text='Alert title', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the alert')),
                ('trigger_event_id', models.UUIDField(blank=True, help_text='Change event that triggered this alert', null=True)),
                ('trigger_event_type', models.CharField(blank=True, help_text='Type of trigger event', max_length=50)),
                ('evidence_id', models.UUIDField(blank=True, help_text='Evidence backing this alert', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how this alert was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, help_text='Analyst assigned to this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dns_intelligence.domain')),
                ('investigation', models.ForeignKey(blank=True, help_text='Associated investigation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='investigation.investigation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', '-created_at'], name='alerts_aler_domain__8bbc41_idx'), models.Index(fields=['owner', 'status'], name='alerts_aler_owner_i_cf5101_idx'), models.Index(fields=['status', 'severity'], name='alerts_aler_status_58cd09_idx'), models.Index(fields=['alert_type', '-created_at'], name='alerts_aler_alert_t_b7affd_idx'), models.Index(fields=['assigned_analyst'], name='alerts_aler_assigne_a36b43_idx'), models.Index(fields=['investigation'], name='alerts_aler_investi_e5a869_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Rule name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Rule description')),
                ('alert_type', models.CharField(choices=[('DNS_RECORD_ADDED', 'DNS Record Added'), ('DNS_RECORD_REMOVED', 'DNS Record Removed'), ('DNS_RECORD_CHANGED', 'DNS Record Changed'), ('IP_CHANGED', 'IP Changed'), ('CERTIFICATE_CHANGED', 'Certificate Changed'), ('CERTIFICATE_EXPIRED', 'Certificate Expired'), ('CERTIFICATE_EXPIRING_SOON', 'Certificate Expiring Soon'), ('SERVICE_APPEARED', 'Service Appeared'), ('SERVICE_DISAPPEARED', 'Service Disappeared'), ('ASN_CHANGED', 'ASN Changed'), ('PROVIDER_CHANGED', 'Provider Changed'), ('LIFECYCLE_CHANGED', 'Lifecycle Changed')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('apply_to_all_domains', models.BooleanField(default=False, help_text='Apply to all user domains')),
                ('specific_domains', models.JSONField(blank=True, default=list, help_text='List of domain IDs to apply to')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'enabled'], name='alerts_aler_owner_i_118bbe_idx'), models.Index(fields=['alert_type'], name='alerts_aler_alert_t_c1d3c0_idx')],
            },
        ),
    ]
