# Generated by Django 5.0.6 on 2026-09-11 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monitor_type', models.CharField(choices=[('DNS', 'DNS'), ('IP', 'IP Address'), ('CERTIFICATE', 'Certificate'), ('SERVICE', 'Service'), ('ASN', 'ASN/Provider'), ('LIFECYCLE', 'Lifecycle')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='DAILY', max_length=20)),
                ('alert_on_change', models.BooleanField(default=True)),
                ('alert_on_failure', models.BooleanField(default=False)),
                ('next_check_scheduled', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_check_completed', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_configs', to='dns_intelligence.domain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monitor_type', models.CharField(choices=[('DNS', 'DNS'), ('IP', 'IP Address'), ('CERTIFICATE', 'Certificate'), ('SERVICE', 'Service'), ('ASN', 'ASN/Provider'), ('LIFECYCLE', 'Lifecycle')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial')], max_length=20)),
                ('observation_id', models.UUIDField(blank=True, help_text='ID of the observation this check is based on', null=True)),
                ('observation_type', models.CharField(blank=True, help_text='Type of observation (DNSObservation, etc.)', max_length=50)),
                ('previous_state', models.JSONField(blank=True, default=dict, help_text='Previous state snapshot')),
                ('new_state', models.JSONField(blank=True, default=dict, help_text='New state snapshot')),
                ('has_changes', models.BooleanField(default=False)),
                ('evidence_id', models.UUIDField(blank=True, help_text='Evidence ID for this observation', null=True)),
                ('scan_job_id', models.UUIDField(blank=True, help_text='ScanJob that performed this check', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('check_started_at', models.DateTimeField()),
                ('check_completed_at', models.DateTimeField()),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_results', to='dns_intelligence.domain')),
                ('monitoring_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='monitoring.monitoringconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('DNS_RECORD_ADDED', 'DNS Record Added'), ('DNS_RECORD_REMOVED', 'DNS Record Removed'), ('DNS_RECORD_CHANGED', 'DNS Record Changed'), ('IP_CHANGED', 'IP Changed'), ('CERTIFICATE_CHANGED', 'Certificate Changed'), ('CERTIFICATE_EXPIRED', 'Certificate Expired'), ('SERVICE_APPEARED', 'Service Appeared'), ('SERVICE_DISAPPEARED', 'Service Disappeared'), ('ASN_CHANGED', 'ASN Changed'), ('PROVIDER_CHANGED', 'Provider Changed'), ('LIFECYCLE_CHANGED', 'Lifecycle Changed')], max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the change')),
                ('previous_value', models.TextField(blank=True, help_text='Previous value (serialized if complex)')),
                ('new_value', models.TextField(blank=True, help_text='New value (serialized if complex)')),
                ('entity_name', models.CharField(blank=True, help_text='Name of the entity that changed', max_length=255)),
                ('entity_type', models.CharField(blank=True, help_text='Type of entity (DNS record, IP, etc.)', max_length=50)),
                ('evidence_id', models.UUIDField(blank=True, help_text='Evidence ID backing this change', null=True)),
                ('alert_generated', models.BooleanField(default=False)),
                ('alert_id', models.UUIDField(blank=True, help_text='Alert generated from this event', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='dns_intelligence.domain')),
                ('monitoring_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='monitoring.monitoringresult')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='monitoringconfig',
            index=models.Index(fields=['domain', 'monitor_type'], name='monitoring__domain__6f8318_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringconfig',
            index=models.Index(fields=['owner', 'is_enabled'], name='monitoring__owner_i_4e979a_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringconfig',
            index=models.Index(fields=['next_check_scheduled'], name='monitoring__next_ch_946684_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoringconfig',
            unique_together={('domain', 'monitor_type', 'owner')},
        ),
        migrations.AddIndex(
            model_name='monitoringresult',
            index=models.Index(fields=['domain', '-created_at'], name='monitoring__domain__a246f7_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringresult',
            index=models.Index(fields=['monitoring_config', '-created_at'], name='monitoring__monitor_40c918_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringresult',
            index=models.Index(fields=['monitor_type', '-created_at'], name='monitoring__monitor_6179fd_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringresult',
            index=models.Index(fields=['status'], name='monitoring__status_12ae27_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoringresult',
            index=models.Index(fields=['has_changes'], name='monitoring__has_cha_571f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['domain', '-detected_at'], name='monitoring__domain__c232b7_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['monitoring_result', '-detected_at'], name='monitoring__monitor_821119_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['event_type', '-detected_at'], name='monitoring__event_t_c8960d_idx'),
        ),
        migrations.AddIndex(
            model_name='changeevent',
            index=models.Index(fields=['alert_generated'], name='monitoring__alert_g_395687_idx'),
        ),
    ]
