# Generated by Django 5.0.6 on 2026-09-08 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Certificate subject (CN or SAN)', max_length=255)),
                ('issuer', models.CharField(help_text='Certificate issuer', max_length=255)),
                ('serial_number', models.CharField(help_text='Certificate serial number', max_length=64)),
                ('fingerprint', models.CharField(help_text='SHA-1 fingerprint', max_length=64)),
                ('fingerprint_sha256', models.CharField(help_text='SHA-256 fingerprint', max_length=64)),
                ('valid_from', models.DateTimeField(help_text='Certificate validity start')),
                ('valid_until', models.DateTimeField(help_text='Certificate validity end')),
                ('sans', models.JSONField(default=list, help_text='List of Subject Alternative Names')),
                ('public_key_algorithm', models.CharField(blank=True, help_text='Public key algorithm (RSA, ECDSA, etc.)', max_length=50)),
                ('public_key_size', models.IntegerField(blank=True, help_text='Public key size in bits', null=True)),
                ('tls_version', models.CharField(blank=True, help_text='TLS version used', max_length=20)),
                ('cipher_suite', models.CharField(blank=True, help_text='Cipher suite used', max_length=100)),
                ('is_valid', models.BooleanField(default=True, help_text='Whether the certificate is currently valid')),
                ('is_expired', models.BooleanField(default=False, help_text='Whether the certificate has expired')),
                ('is_self_signed', models.BooleanField(default=False, help_text='Whether the certificate is self-signed')),
                ('source', models.CharField(default='TLS Handshake', help_text='Source of certificate data', max_length=100)),
                ('collection_timestamp', models.DateTimeField(auto_now_add=True, help_text='When this certificate was collected')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['domain', '-last_seen'], name='certificate_domain__9d4c75_idx'), models.Index(fields=['valid_until'], name='certificate_valid_u_16a696_idx'), models.Index(fields=['issuer'], name='certificate_issuer_2295f3_idx')],
                'unique_together': {('domain', 'fingerprint_sha256')},
            },
        ),
        migrations.CreateModel(
            name='CertificateObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=64)),
                ('fingerprint', models.CharField(max_length=64)),
                ('fingerprint_sha256', models.CharField(max_length=64)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('sans', models.JSONField(default=list)),
                ('public_key_algorithm', models.CharField(blank=True, max_length=50)),
                ('public_key_size', models.IntegerField(blank=True, null=True)),
                ('tls_version', models.CharField(blank=True, max_length=20)),
                ('cipher_suite', models.CharField(blank=True, max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_self_signed', models.BooleanField(default=False)),
                ('source', models.CharField(default='TLS Handshake', max_length=100)),
                ('collection_method', models.CharField(blank=True, help_text='How the certificate was collected', max_length=100)),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='HIGH', max_length=10)),
                ('observed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_observations', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['domain', 'fingerprint_sha256', 'observed_at'], name='certificate_domain__d24457_idx'), models.Index(fields=['domain', '-observed_at'], name='certificate_domain__5ed6b4_idx'), models.Index(fields=['valid_until'], name='certificate_valid_u_e69390_idx')],
            },
        ),
    ]
