# Generated by Django 5.0.6 on 2026-09-06 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Investigation title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Investigation description')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('related_evidence', models.JSONField(blank=True, default=list, help_text='List of evidence IDs related to this investigation')),
                ('related_alerts', models.JSONField(blank=True, default=list, help_text='List of alert IDs related to this investigation')),
                ('important_observations', models.TextField(blank=True, help_text='Key observations from the investigation')),
                ('limitations', models.TextField(blank=True, help_text='Known limitations or missing information')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the investigation was closed', null=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, help_text='Analyst assigned to this investigation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_investigations', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='dns_intelligence.domain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalystNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Note content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyst_notes', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='investigation.investigation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['domain', '-created_at'], name='investigati_domain__f03ead_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['owner', 'status'], name='investigati_owner_i_abd492_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['status', 'priority'], name='investigati_status_f3a297_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['assigned_analyst'], name='investigati_assigne_6600f8_idx'),
        ),
        migrations.AddIndex(
            model_name='analystnote',
            index=models.Index(fields=['investigation', '-created_at'], name='investigati_investi_25f7cd_idx'),
        ),
        migrations.AddIndex(
            model_name='analystnote',
            index=models.Index(fields=['author', '-created_at'], name='investigati_author__0d4ef1_idx'),
        ),
    ]
