# Generated by Django 5.0.6 on 2026-09-06 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_username', models.CharField(blank=True, help_text='Username of actor (preserved even if user deleted)', max_length=255)),
                ('event_type', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('REGISTRATION', 'Registration'), ('PASSWORD_CHANGE', 'Password Change'), ('DOMAIN_CREATED', 'Domain Created'), ('DOMAIN_DELETED', 'Domain Deleted'), ('DOMAIN_UPDATED', 'Domain Updated'), ('INVESTIGATION_STARTED', 'Investigation Started'), ('INVESTIGATION_COMPLETED', 'Investigation Completed'), ('INVESTIGATION_FAILED', 'Investigation Failed'), ('ALERT_ACKNOWLEDGED', 'Alert Acknowledged'), ('ALERT_RESOLVED', 'Alert Resolved'), ('ALERT_REOPENED', 'Alert Reopened'), ('ANALYST_NOTE_CREATED', 'Analyst Note Created'), ('ANALYST_NOTE_UPDATED', 'Analyst Note Updated'), ('ANALYST_NOTE_DELETED', 'Analyst Note Deleted'), ('SETTINGS_UPDATED', 'Settings Updated'), ('REPORT_GENERATED', 'Report Generated'), ('REPORT_EXPORTED', 'Report Exported'), ('OTHER', 'Other')], max_length=50)),
                ('action', models.CharField(help_text='Description of the action performed', max_length=255)),
                ('resource_type', models.CharField(blank=True, help_text="Type of resource affected (e.g., 'Domain', 'Investigation')", max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='ID of the affected resource', max_length=255)),
                ('resource_name', models.CharField(blank=True, help_text='Human-readable name of the resource', max_length=255)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('PARTIAL', 'Partial')], default='SUCCESS', max_length=20)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code or similar', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured metadata about the event')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='accounts_au_actor_i_cae179_idx'), models.Index(fields=['event_type', '-timestamp'], name='accounts_au_event_t_784a60_idx'), models.Index(fields=['resource_type', 'resource_id'], name='accounts_au_resourc_9749c3_idx'), models.Index(fields=['result', '-timestamp'], name='accounts_au_result_ae8f91_idx'), models.Index(fields=['timestamp'], name='accounts_au_timesta_3e3b1c_idx')],
            },
        ),
    ]
