# Generated by Django 5.0.6 on 2026-09-06 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_format', models.CharField(choices=[('ISO_8601', 'ISO 8601 (YYYY-MM-DD)'), ('US', 'US (MM/DD/YYYY)'), ('EUROPEAN', 'European (DD/MM/YYYY)')], default='ISO_8601', max_length=20)),
                ('time_format', models.CharField(choices=[('24_HOUR', '24-hour'), ('12_HOUR', '12-hour')], default='24_HOUR', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('auto_refresh', models.BooleanField(default=False)),
                ('refresh_interval_minutes', models.IntegerField(default=5)),
                ('default_monitoring_behavior', models.CharField(choices=[('PASSIVE', 'Passive (observation only)'), ('ACTIVE', 'Active (periodic scanning)')], default='PASSIVE', max_length=20)),
                ('email_alerts', models.BooleanField(default=False)),
                ('alert_severity_threshold', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='HIGH', max_length=10)),
                ('session_timeout_minutes', models.IntegerField(default=60)),
                ('default_dashboard_view', models.CharField(blank=True, default='overview', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
