# Generated by Django 5.0.6 on 2026-08-28 14:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dns_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField(db_index=True)),
                ('asn', models.CharField(blank=True, max_length=32, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=8, null=True)),
                ('reverse_dns', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(default='RDAP', max_length=64)),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM', max_length=10)),
                ('lookup_succeeded', models.BooleanField(default=True)),
                ('error_detail', models.CharField(blank=True, max_length=255)),
                ('observed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_observations', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['domain', 'address', 'observed_at'], name='infrastruct_domain__ad5f08_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.GenericIPAddressField(db_index=True)),
                ('version', models.CharField(choices=[('IPv4', 'IPv4'), ('IPv6', 'IPv6')], max_length=4)),
                ('association_status', models.CharField(choices=[('CURRENT', 'Current'), ('HISTORICAL', 'Historical'), ('ESTIMATED', 'Estimated'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12)),
                ('reverse_dns', models.CharField(blank=True, max_length=255, null=True)),
                ('asn', models.CharField(blank=True, max_length=32, null=True)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=8, null=True)),
                ('is_likely_cdn', models.BooleanField(default=False)),
                ('is_likely_shared_hosting', models.BooleanField(default=False)),
                ('cdn_indicator_source', models.CharField(blank=True, max_length=255)),
                ('rdap_available', models.BooleanField(default=False, help_text='False if RDAP lookup failed/unavailable — ownership fields must not be trusted.')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='dns_intelligence.domain')),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('domain', 'address')},
            },
        ),
    ]
