# Generated by Django 5.0.6 on 2026-09-11 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Report title', max_length=255)),
                ('domains', models.JSONField(default=list, help_text='List of domain IDs included in report')),
                ('scope_description', models.TextField(blank=True, help_text='Description of report scope')),
                ('format', models.CharField(choices=[('JSON', 'JSON'), ('HTML', 'HTML'), ('PDF', 'PDF')], default='JSON', max_length=10)),
                ('requested_sections', models.JSONField(default=list, help_text='List of sections to include')),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for generation', max_length=255)),
                ('content', models.JSONField(blank=True, default=dict, help_text='Generated report content')),
                ('content_html', models.TextField(blank=True, help_text='HTML content for HTML reports')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Report metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('EXECUTIVE_SUMMARY', 'Executive Summary'), ('SCOPE', 'Scope'), ('ASSETS', 'Assets'), ('DNS', 'DNS'), ('CERTIFICATES', 'Certificates'), ('INFRASTRUCTURE', 'Infrastructure'), ('SERVICES', 'Services'), ('LIFECYCLE', 'Lifecycle'), ('MONITORING', 'Monitoring'), ('ALERTS', 'Alerts'), ('HISTORY', 'History'), ('EVIDENCE', 'Evidence'), ('FINDINGS', 'Findings'), ('RECOMMENDATIONS', 'Recommendations'), ('LIMITATIONS', 'Limitations')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Section content')),
                ('evidence_ids', models.JSONField(default=list, help_text='List of evidence IDs supporting this section')),
                ('observation_ids', models.JSONField(default=list, help_text='List of observation IDs referenced')),
                ('findings', models.JSONField(default=list, help_text='List of findings with provenance')),
                ('status', models.CharField(choices=[('OBSERVED', 'Observed'), ('HISTORICAL', 'Historical'), ('INFERRED', 'Inferred'), ('ANALYST', 'Analyst'), ('UNKNOWN', 'Unknown')], default='OBSERVED', help_text='Classification of findings in this section', max_length=20)),
                ('confidence', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='MEDIUM', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Section order within report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'INFO'), ('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='MEDIUM', max_length=20)),
                ('source_observation_id', models.UUIDField(blank=True, help_text='ID of source observation', null=True)),
                ('source_observation_type', models.CharField(blank=True, help_text='Type of source observation', max_length=50)),
                ('evidence_id', models.UUIDField(blank=True, help_text='Evidence ID backing this finding', null=True)),
                ('asset_id', models.UUIDField(blank=True, help_text='Asset ID (domain, IP, etc.)', null=True)),
                ('asset_name', models.CharField(blank=True, help_text='Asset name', max_length=255)),
                ('asset_type', models.CharField(blank=True, help_text='Asset type', max_length=50)),
                ('finding_status', models.CharField(choices=[('OBSERVED', 'Observed'), ('HISTORICAL', 'Historical'), ('INFERRED', 'Inferred'), ('ANALYST', 'Analyst'), ('UNKNOWN', 'Unknown')], default='OBSERVED', max_length=20)),
                ('observed_at', models.DateTimeField(blank=True, help_text='When the finding was observed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional finding metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_findings', to='reports.reportsection')),
            ],
            options={
                'ordering': ['-severity', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['owner', '-created_at'], name='reports_rep_owner_i_aeee04_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['report', 'order'], name='reports_rep_report__06852e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['section_type'], name='reports_rep_section_365278_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfinding',
            index=models.Index(fields=['report_section', 'severity'], name='reports_rep_report__a221cb_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfinding',
            index=models.Index(fields=['finding_status'], name='reports_rep_finding_a02a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportfinding',
            index=models.Index(fields=['asset_id'], name='reports_rep_asset_i_e4beb2_idx'),
        ),
    ]
